# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2df09647c187ba7b8044f3d2d3754805e00838fa77cbd666f018bc2e802705a60ff7cf786204461aa9228b9631cc76ce9dc1d5dcd9bead20e894020ce4cd8b14

test:
  secret_key_base: 2a1a834347695759fd7c90fe35493f7ed2ea94f406a4f51fcb39431b1bc652251f30d8ca5ae5191272911d57e7bf927b3f3e88cb988502d6fa8767ef8b45ef35

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
